# This workflow will:
# 1. Analyze the project for any issues.
# 2. Deploy migrations to the `development` database.
# 3. Reset the seed data in the `development` database.
# !! NOTE: This will reset all the seed data in the development database.

name: Push database changes to supabase

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/db/supabase/migrations/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      SUPABASE_PROJECT_ID: ${{ secrets.DEVELOP_SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.DEVELOP_SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DATABASE_URL: ${{ secrets.DEVELOP_DATABASE_URL }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DEVELOP_DB_PASSWORD }}
      DATABASE_URL: ${{ secrets.DEVELOP_DATABASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun Environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          cache: true
      
      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Reset database
        run: echo 'y' | supabase db reset --db-url "$SUPABASE_DATABASE_URL" --workdir=src

      - name: Deploy migrations
        run: supabase db push --db-url "$SUPABASE_DATABASE_URL" --workdir=src

      - name: Reset seed data
        run: bun run db:seed
